services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hello_rust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5da715e0-24ac-48a7-8998-5f7821bbf79f
    ports:
      - "5432:5432"
    volumes:
      - D:/database/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"
    volumes:
      - D:/database/redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
